[workspace]
title = "PoC"
packages = ["integrations/mcp_server", "integrations/hr_chat_assistant", "integrations/hubspot_to_oracledb", "integrations/rag_ingestion", "integrations/sap_ecc_events", "integrations/sap_client"]
